// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: aux/common.proto

package aux

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Platform int32

const (
	Platform_IOS   Platform = 1
	Platform_DROID Platform = 2
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		1: "IOS",
		2: "DROID",
	}
	Platform_value = map[string]int32{
		"IOS":   1,
		"DROID": 2,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_aux_common_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_aux_common_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Platform) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Platform(num)
	return nil
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_aux_common_proto_rawDescGZIP(), []int{0}
}

type DeviceFormFactor int32

const (
	DeviceFormFactor_PHONE  DeviceFormFactor = 1
	DeviceFormFactor_TABLET DeviceFormFactor = 2
)

// Enum value maps for DeviceFormFactor.
var (
	DeviceFormFactor_name = map[int32]string{
		1: "PHONE",
		2: "TABLET",
	}
	DeviceFormFactor_value = map[string]int32{
		"PHONE":  1,
		"TABLET": 2,
	}
)

func (x DeviceFormFactor) Enum() *DeviceFormFactor {
	p := new(DeviceFormFactor)
	*p = x
	return p
}

func (x DeviceFormFactor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceFormFactor) Descriptor() protoreflect.EnumDescriptor {
	return file_aux_common_proto_enumTypes[1].Descriptor()
}

func (DeviceFormFactor) Type() protoreflect.EnumType {
	return &file_aux_common_proto_enumTypes[1]
}

func (x DeviceFormFactor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DeviceFormFactor) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DeviceFormFactor(num)
	return nil
}

// Deprecated: Use DeviceFormFactor.Descriptor instead.
func (DeviceFormFactor) EnumDescriptor() ([]byte, []int) {
	return file_aux_common_proto_rawDescGZIP(), []int{1}
}

type AdNetwork int32

const (
	AdNetwork_VUNGLE     AdNetwork = 0
	AdNetwork_CHARTBOOST AdNetwork = 1
	AdNetwork_AD_COLONY  AdNetwork = 2
	AdNetwork_HYPER_MX   AdNetwork = 3
	AdNetwork_UNITY      AdNetwork = 4
	AdNetwork_FACEBOOK   AdNetwork = 5
	AdNetwork_APPLOVIN   AdNetwork = 6
)

// Enum value maps for AdNetwork.
var (
	AdNetwork_name = map[int32]string{
		0: "VUNGLE",
		1: "CHARTBOOST",
		2: "AD_COLONY",
		3: "HYPER_MX",
		4: "UNITY",
		5: "FACEBOOK",
		6: "APPLOVIN",
	}
	AdNetwork_value = map[string]int32{
		"VUNGLE":     0,
		"CHARTBOOST": 1,
		"AD_COLONY":  2,
		"HYPER_MX":   3,
		"UNITY":      4,
		"FACEBOOK":   5,
		"APPLOVIN":   6,
	}
)

func (x AdNetwork) Enum() *AdNetwork {
	p := new(AdNetwork)
	*p = x
	return p
}

func (x AdNetwork) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdNetwork) Descriptor() protoreflect.EnumDescriptor {
	return file_aux_common_proto_enumTypes[2].Descriptor()
}

func (AdNetwork) Type() protoreflect.EnumType {
	return &file_aux_common_proto_enumTypes[2]
}

func (x AdNetwork) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AdNetwork) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AdNetwork(num)
	return nil
}

// Deprecated: Use AdNetwork.Descriptor instead.
func (AdNetwork) EnumDescriptor() ([]byte, []int) {
	return file_aux_common_proto_rawDescGZIP(), []int{2}
}

var File_aux_common_proto protoreflect.FileDescriptor

var file_aux_common_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x75, 0x78, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x75, 0x78, 0x2a, 0x1e, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4f, 0x53, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x44, 0x52, 0x4f, 0x49, 0x44, 0x10, 0x02, 0x2a, 0x29, 0x0a, 0x10, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x46, 0x6f, 0x72, 0x6d, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x09, 0x0a, 0x05, 0x50,
	0x48, 0x4f, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x54,
	0x10, 0x02, 0x2a, 0x6b, 0x0a, 0x09, 0x41, 0x64, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12,
	0x0a, 0x0a, 0x06, 0x56, 0x55, 0x4e, 0x47, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x43,
	0x48, 0x41, 0x52, 0x54, 0x42, 0x4f, 0x4f, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x41,
	0x44, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x4e, 0x59, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x48, 0x59,
	0x50, 0x45, 0x52, 0x5f, 0x4d, 0x58, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x49, 0x54,
	0x59, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x41, 0x43, 0x45, 0x42, 0x4f, 0x4f, 0x4b, 0x10,
	0x05, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x50, 0x50, 0x4c, 0x4f, 0x56, 0x49, 0x4e, 0x10, 0x06, 0x42,
	0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61,
	0x6e, 0x61, 0x74, 0x69, 0x63, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x45, 0x67,
	0x67, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x65, 0x72, 0x2f, 0x61, 0x75, 0x78,
}

var (
	file_aux_common_proto_rawDescOnce sync.Once
	file_aux_common_proto_rawDescData = file_aux_common_proto_rawDesc
)

func file_aux_common_proto_rawDescGZIP() []byte {
	file_aux_common_proto_rawDescOnce.Do(func() {
		file_aux_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_aux_common_proto_rawDescData)
	})
	return file_aux_common_proto_rawDescData
}

var file_aux_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_aux_common_proto_goTypes = []interface{}{
	(Platform)(0),         // 0: aux.Platform
	(DeviceFormFactor)(0), // 1: aux.DeviceFormFactor
	(AdNetwork)(0),        // 2: aux.AdNetwork
}
var file_aux_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aux_common_proto_init() }
func file_aux_common_proto_init() {
	if File_aux_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aux_common_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aux_common_proto_goTypes,
		DependencyIndexes: file_aux_common_proto_depIdxs,
		EnumInfos:         file_aux_common_proto_enumTypes,
	}.Build()
	File_aux_common_proto = out.File
	file_aux_common_proto_rawDesc = nil
	file_aux_common_proto_goTypes = nil
	file_aux_common_proto_depIdxs = nil
}
